/**
 * Build twm's dist/.
 *
 *     node build.mjs            # write dist/
 *     node build.mjs --check    # build to memory and fail if dist/ is stale
 *
 * The packaging decision (docs/UI_FRAMEWORK_EXTRACTION.md §6) is PREBUILT DIST:
 * this repo owns the build and COMMITS dist/, so EcoAgent — which has no
 * package.json, no node_modules and no bundler — consumes the library through
 * its existing import map and stays zero-build. npm consumers get the same
 * artifact with semver.
 *
 * Four entry points, not one. A consumer who wants a DataTable should not have
 * to download the window manager. esbuild's `splitting` factors the shared
 * modules (event_bus, logging, the component base classes) into chunks that any
 * subset of the entries can pull in, so importing two entries does NOT give you
 * two copies of the event bus — which would give you two copies of every
 * module-level singleton, and a settings store that silently forgets writes.
 */

import { build } from 'esbuild';
import { readFile, writeFile, mkdir, readdir, unlink } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const CHECK = process.argv.includes('--check');

const ENTRIES = ['core', 'host', 'wm', 'widgets', 'charts', 'tiles', 'editor'];

const result = await build({
    entryPoints: ENTRIES.map((e) => join(HERE, `${e}.js`)),
    outdir: join(HERE, 'dist'),
    bundle: true,
    splitting: true,          // shared chunks — see the note above, it is load-bearing
    format: 'esm',
    target: 'es2022',         // what the app's webview actually runs
    platform: 'browser',
    // The kernel has ZERO external dependencies — no CodeMirror, no Monaco, no
    // Plotly. If that ever stops being true this build starts failing on an
    // unresolved bare specifier, which is exactly the alarm we want.
    external: [],
    minify: false,            // a UI library people will debug in a webview
    sourcemap: true,
    legalComments: 'inline',
    metafile: true,
    write: !CHECK,
    logLevel: 'info',
});

// ── the stylesheet ──────────────────────────────────────────────────────────
// GENERATED upstream by scripts/css_extract.py, which decides ownership by USE
// (which JS applies a class) rather than by which file a rule happens to sit in.
// Three files, and that is the whole CSS contract:
//   tokens.css  every twm rule reads var(--…) from here — swap it, restyle everything
//   reset.css   the reset
//   flexdesk.css the library, GENERATED by scripts/css_extract.py, which decides
//               ownership by USE (which JS applies a class) rather than by which
//               file a rule happens to sit in
const STYLES = ['tokens.css', 'reset.css', 'flexdesk.css'];
const css = await readFile(join(HERE, 'css', 'flexdesk.css'), 'utf8');
if (!CHECK) {
    await mkdir(join(HERE, 'dist'), { recursive: true });
    for (const f of STYLES) {
        await writeFile(join(HERE, 'dist', f), await readFile(join(HERE, 'css', f), 'utf8'));
    }
}

// ── prune orphaned chunks ───────────────────────────────────────────────────
// ESBUILD NAMES CHUNKS BY CONTENT HASH AND NEVER REMOVES THE OLD ONE. A chunk
// is `chunk-AYV27FQG.js` only for as long as its contents hash to that; edit
// any module inside it and the next build writes a NEW file and leaves the
// previous one sitting in dist/ forever. After enough builds dist/ held 58
// chunks of which 11 were reachable — the other 47 were fossils, and among
// them were ELEVEN different copies of ManagedWindow.
//
// That is not merely bloat, it is a trap with teeth: a consumer debugging the
// window manager greps dist/ for `minimize()`, finds it in a fossil, and reads
// code that has not run in weeks. It cost a full diagnosis session downstream
// — a fix verified present in src/, absent from the chunk being grepped, and
// live all along in the chunk actually imported. `--check` could not see it
// either: it asks whether every built file EXISTS, which stays true no matter
// how many dead ones sit beside them.
//
// So the build now owns removal as well as writing.
//
// AND IT IS NOT ONLY `chunk-*`. This pattern read `^chunk-` for one release
// and missed the other half of esbuild's hashed output: a DYNAMIC import is
// emitted under its own module's name, hashed the same way. `tile_grid.js`
// does `await import('./tile_registry.js')`, so dist/ carries
// `tile_registry-<HASH>.js` — matched by neither the pruner nor `--check`,
// copied faithfully into a consumer's vendor/ by its refresh script, and
// invisible to the `diff -rq vendor dist` that is supposed to be the alarm,
// because vendor mirrored dist exactly and dist was the thing carrying the
// fossils. Every edit to the tile registry would have left another greppable
// copy behind, in the file a dashboard's whole widget catalogue resolves
// through — the worst possible place to hand someone last week's code.
//
// So the test is the SHAPE of a hashed name, `<name>-<8 base32 chars>.js`,
// which covers both kinds and nothing else: the entry points are stable names
// with no hash (`wm.js`, `tiles.js`), the stylesheets are not `.js` at all,
// and anything currently produced is exempted by `produced` regardless.
const HASHED_OUTPUT_RE = /^[^/]+-[A-Z0-9]{8}\.js(\.map)?$/;
if (!CHECK) {
    const produced = new Set(Object.keys(result.metafile.outputs)
        .map((f) => f.split('/').pop())
        .flatMap((f) => [f, `${f}.map`]));
    for (const f of await readdir(join(HERE, 'dist'))) {
        if (!HASHED_OUTPUT_RE.test(f) || produced.has(f)) continue;
        await unlink(join(HERE, 'dist', f));
        console.log(`  pruned orphan output ${f}`);
    }
}

// ── report ──────────────────────────────────────────────────────────────────
const outputs = Object.entries(result.metafile.outputs)
    .filter(([f]) => f.endsWith('.js'))
    .sort((a, b) => b[1].bytes - a[1].bytes);

console.log('\n  entry points');
for (const e of ENTRIES) {
    const hit = outputs.find(([f]) => f.endsWith(`/${e}.js`));
    if (hit) console.log(`    @flexdesk/${e.padEnd(8)} ${(hit[1].bytes / 1024).toFixed(1).padStart(7)} kB`);
}
const chunks = outputs.filter(([f]) => /chunk-/.test(f));
if (chunks.length) {
    const total = chunks.reduce((n, [, o]) => n + o.bytes, 0);
    console.log(`  shared chunks: ${chunks.length}  (${(total / 1024).toFixed(1)} kB — imported once, not per entry)`);
}
console.log(`  flexdesk.css   ${(css.length / 1024).toFixed(1).padStart(7)} kB`);

if (CHECK) {
    if (!existsSync(join(HERE, 'dist'))) {
        console.error('\nFAIL: dist/ is missing. Run `node build.mjs` and commit it.');
        process.exit(1);
    }
    const built = new Set(outputs.map(([f]) => f.split('/').pop()));
    const onDisk = new Set((await readdir(join(HERE, 'dist'))).filter((f) => f.endsWith('.js')));
    const missing = [...built].filter((f) => !onDisk.has(f));
    if (missing.length) {
        console.error(`\nFAIL: dist/ is stale — missing ${missing.join(', ')}.`);
        process.exit(1);
    }
    // Orphans are reported rather than failed on: they make dist/ MISLEADING,
    // not wrong, and a consumer pinned to an older dist/ should not have their
    // build broken by fossils a previous build left behind. `node build.mjs`
    // removes them.
    const orphans = [...onDisk].filter(
        (f) => HASHED_OUTPUT_RE.test(f) && !built.has(f));
    if (orphans.length) {
        console.warn(`\nWARN: ${orphans.length} orphaned output(s) in dist/ —`
                   + ` ${orphans.join(', ')} — dead output from earlier builds`
                   + ' that still contains greppable copies of live classes.'
                   + ' Run `node build.mjs`.');
    }
    console.log('\nOK: dist/ is present and matches the entry points.');
}
