/**
 * Build twm's dist/.
 *
 *     node build.mjs            # write dist/
 *     node build.mjs --check    # build to memory and fail if dist/ is stale
 *
 * The packaging decision (docs/UI_FRAMEWORK_EXTRACTION.md §6) is PREBUILT DIST:
 * this repo owns the build and COMMITS dist/, so EcoAgent — which has no
 * package.json, no node_modules and no bundler — consumes the library through
 * its existing import map and stays zero-build. npm consumers get the same
 * artifact with semver.
 *
 * Four entry points, not one. A consumer who wants a DataTable should not have
 * to download the window manager. esbuild's `splitting` factors the shared
 * modules (event_bus, logging, the component base classes) into chunks that any
 * subset of the entries can pull in, so importing two entries does NOT give you
 * two copies of the event bus — which would give you two copies of every
 * module-level singleton, and a settings store that silently forgets writes.
 */

import { build } from 'esbuild';
import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const CHECK = process.argv.includes('--check');

const ENTRIES = ['core', 'host', 'wm', 'widgets', 'charts', 'tiles', 'editor'];

const result = await build({
    entryPoints: ENTRIES.map((e) => join(HERE, `${e}.js`)),
    outdir: join(HERE, 'dist'),
    bundle: true,
    splitting: true,          // shared chunks — see the note above, it is load-bearing
    format: 'esm',
    target: 'es2022',         // what the app's webview actually runs
    platform: 'browser',
    // The kernel has ZERO external dependencies — no CodeMirror, no Monaco, no
    // Plotly. If that ever stops being true this build starts failing on an
    // unresolved bare specifier, which is exactly the alarm we want.
    external: [],
    minify: false,            // a UI library people will debug in a webview
    sourcemap: true,
    legalComments: 'inline',
    metafile: true,
    write: !CHECK,
    logLevel: 'info',
});

// ── the stylesheet ──────────────────────────────────────────────────────────
// GENERATED upstream by scripts/css_extract.py, which decides ownership by USE
// (which JS applies a class) rather than by which file a rule happens to sit in.
// Three files, and that is the whole CSS contract:
//   tokens.css  every twm rule reads var(--…) from here — swap it, restyle everything
//   reset.css   the reset
//   flexdesk.css the library, GENERATED by scripts/css_extract.py, which decides
//               ownership by USE (which JS applies a class) rather than by which
//               file a rule happens to sit in
const STYLES = ['tokens.css', 'reset.css', 'flexdesk.css'];
const css = await readFile(join(HERE, 'css', 'flexdesk.css'), 'utf8');
if (!CHECK) {
    await mkdir(join(HERE, 'dist'), { recursive: true });
    for (const f of STYLES) {
        await writeFile(join(HERE, 'dist', f), await readFile(join(HERE, 'css', f), 'utf8'));
    }
}

// ── report ──────────────────────────────────────────────────────────────────
const outputs = Object.entries(result.metafile.outputs)
    .filter(([f]) => f.endsWith('.js'))
    .sort((a, b) => b[1].bytes - a[1].bytes);

console.log('\n  entry points');
for (const e of ENTRIES) {
    const hit = outputs.find(([f]) => f.endsWith(`/${e}.js`));
    if (hit) console.log(`    @flexdesk/${e.padEnd(8)} ${(hit[1].bytes / 1024).toFixed(1).padStart(7)} kB`);
}
const chunks = outputs.filter(([f]) => /chunk-/.test(f));
if (chunks.length) {
    const total = chunks.reduce((n, [, o]) => n + o.bytes, 0);
    console.log(`  shared chunks: ${chunks.length}  (${(total / 1024).toFixed(1)} kB — imported once, not per entry)`);
}
console.log(`  flexdesk.css   ${(css.length / 1024).toFixed(1).padStart(7)} kB`);

if (CHECK) {
    if (!existsSync(join(HERE, 'dist'))) {
        console.error('\nFAIL: dist/ is missing. Run `node build.mjs` and commit it.');
        process.exit(1);
    }
    const built = new Set(outputs.map(([f]) => f.split('/').pop()));
    const onDisk = new Set((await readdir(join(HERE, 'dist'))).filter((f) => f.endsWith('.js')));
    const missing = [...built].filter((f) => !onDisk.has(f));
    if (missing.length) {
        console.error(`\nFAIL: dist/ is stale — missing ${missing.join(', ')}.`);
        process.exit(1);
    }
    console.log('\nOK: dist/ is present and matches the entry points.');
}
