/**
 * @flexdesk/canvas — the canvas kernel: a pannable, zoomable surface with
 * marquee selection, the edge router (orthogonal routing, crow's feet, a
 * loop's return line, a layered Arrange) and a generic graph layer (nodes and
 * their ports, connection legality with a policy hook, snapshot-free history
 * over a closed action list).
 *
 * It knows nothing about what the nodes ARE. A consumer's own rules — which
 * ports connect, what a collapsed node shows — are subclasses and policies it
 * passes in.
 *
 * HAND-WRITTEN, not generated. The other barrels say "GENERATED by
 * scripts/gen_barrels.py", and that script is not in this repository (nor is
 * scripts/css_extract.py), so this one is kept by hand: add a module here when
 * you add one under src/canvas/.
 */

export * from './src/canvas/index.js';
