/**
 * @flexdesk/charts — Plotly-backed charts: the wrapper, the chart types, subplot layouts,
 * downsampling, and the two plot windows.
 *
 * Plotly is a PEER dependency — 4.4 MB this bundle deliberately does NOT
 * contain. Call setPlotlySource() with the path to your copy.
 *
 * GENERATED by scripts/gen_barrels.py. Do not hand-edit.
 *
 * 6 modules.
 */

export * from './src/charts/chart_types.js';
export * from './src/charts/data_series_plot_window.js';
export * from './src/charts/downsample.js';
export * from './src/charts/plot_config.js';
export * from './src/charts/plot_popout_window.js';
export * from './src/charts/plotly_wrapper.js';
