/**
 * @flexdesk/editor — A Monaco-backed multi-file editor: the loader, the editor factory, the
 * tab bar, search, a split-pane container and an undo manager.
 *
 * Monaco is a PEER dependency — 14 MB this bundle deliberately does NOT
 * contain, and whose location it refuses to guess. Call setMonacoBasePath()
 * and setDefaultLanguage().
 *
 * GENERATED by scripts/gen_barrels.py. Do not hand-edit.
 *
 * 7 modules.
 */

export * from './src/editor/editor_pane.js';
export * from './src/editor/monaco_editor_factory.js';
export * from './src/editor/monaco_loader.js';
export * from './src/editor/notebook_search.js';
export * from './src/editor/notebook_tab_bar.js';
export * from './src/editor/notebook_undo_manager.js';
export * from './src/editor/split_pane_container.js';
