/**
 * @flexdesk/flow — flow editors: the shared kit (a step-type catalogue, a
 * settings panel generated from a JSON-Schema subset, a widget registry,
 * reference chips, the step and value pickers, findings, undo over whole
 * snapshots, keys) and the three editors built on it — the canvas, the outline
 * and the lanes.
 *
 * Every editor is domain-neutral: it never fetches, never saves and never
 * names a consumer's vocabulary. The step types, the reference grammar, every
 * finding and every byte of I/O are the consumer's, passed in.
 *
 * HAND-WRITTEN, not generated. The other barrels say "GENERATED by
 * scripts/gen_barrels.py", and that script is not in this repository, so this
 * one is kept by hand. Each line below is one owner's module (36 §2): the kit
 * is laid down first, and each editor fills its own index.js.
 */

export * from './src/flow/kit/index.js';
export * from './src/flow/canvas_editor/index.js';
export * from './src/flow/outline/index.js';
export * from './src/flow/lanes/index.js';
