/**
 * @flexdesk/host — The host port. The library never touches pywebview, fetch or localStorage
 * directly — it asks a Host, and the application supplies one.
 *
 * GENERATED by scripts/gen_barrels.py. Do not hand-edit.
 *
 * 2 modules.
 */

export * from './src/host/host.js';
export * from './src/host/pywebview_host.js';
