/**
 * @flexdesk/tiles — A draggable, resizable widget grid: the tile base class, the grid, the
 * widget registry, and layout persistence.
 *
 * It stores layouts under keys YOU choose and resolves starting templates
 * through a callback YOU supply. It has no opinion about what a layout is
 * keyed by.
 *
 * GENERATED by scripts/gen_barrels.py. Do not hand-edit.
 *
 * 5 modules.
 */

export * from './src/tiles/config_schema.js';
export * from './src/tiles/layout_persistence.js';
export * from './src/tiles/tile_base.js';
export * from './src/tiles/tile_grid.js';
export * from './src/tiles/tile_registry.js';
