/**
 * @flexdesk/wm — The tiling window manager: tiles, tabs, splits, desktops, the command
 * palette, the taxonomy and entity registries, and createShell().
 *
 * GENERATED by scripts/gen_barrels.py. Do not hand-edit.
 *
 * 17 modules.
 */

export * from './src/tiling/command_palette.js';
export * from './src/tiling/content_registry.js';
export * from './src/tiling/desktops.js';
export * from './src/tiling/entity_sources.js';
export * from './src/tiling/keymap.js';
export * from './src/tiling/kind_taxonomy.js';
export * from './src/tiling/landing_table.js';
export * from './src/tiling/loading_overlay.js';
export * from './src/tiling/nav_panel.js';
export * from './src/tiling/page_factory.js';
export * from './src/tiling/panel_keys.js';
export * from './src/tiling/shell.js';
export * from './src/tiling/tile_breadcrumb.js';
export * from './src/tiling/tile_renderer.js';
export * from './src/tiling/tile_tab_menu.js';
export * from './src/tiling/tile_tree.js';
export * from './src/tiling/wm.js';
