/**
 * THE SCAFFOLDING THE THREE EDITORS BUILD IN (36 §2) — the lines every
 * branch shares, laid down once by the kit so no two branches edit one line.
 *
 *   §1  the two barrels: @flexdesk/canvas re-exports src/canvas/index.js;
 *       @flexdesk/flow re-exports the kit and each editor's index.js
 *   §2  package.json exports both, with an `import` (dist) and a
 *       `development` (source) condition; build.mjs builds both
 *   §3  the stylesheet: four delimited sections at the END of flexdesk.css,
 *       in order, TWO blank lines apart (so three branches inserting in three
 *       sections merge without a conflict) — and base.css carries the same
 *       four, byte for byte (css/flexdesk.css is generated by a script that is
 *       not in the repository, so the two are mirrored by hand)
 *   §4  tokens.css defines every tone the kit names, every part of each
 *   §5  the README has the "Flow editors" section with its four subsections
 *   §6  the kit's public API is the contract's (36 §3): every name it lists
 *
 *     node tests/flow_kit_scaffold.test.mjs
 */
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { assertions } from './flow_env.mjs';

const t = assertions('flow kit — scaffolding');
const has = (rel) => existsSync(join(t.root, rel));

t.section('§1 the barrels');
{
    const canvas = t.read('canvas.js');
    const flow = t.read('flow.js');
    t.ok('canvas.js re-exports src/canvas/index.js', /export \* from '\.\/src\/canvas\/index\.js';/.test(canvas));
    for (const part of ['kit', 'canvas_editor', 'outline', 'lanes']) {
        t.ok(`flow.js re-exports src/flow/${part}/index.js`,
             new RegExp(`export \\* from '\\./src/flow/${part}/index\\.js';`).test(flow));
        t.ok(`src/flow/${part}/index.js exists`, has(`src/flow/${part}/index.js`));
    }
    t.ok('src/canvas/index.js exists', has('src/canvas/index.js'));
    t.ok('both barrels say they are hand-written, not generated', /HAND-WRITTEN/.test(canvas) && /HAND-WRITTEN/.test(flow)
         && !/GENERATED by scripts\/gen_barrels/.test(canvas) && !/GENERATED by scripts\/gen_barrels/.test(flow));
}

t.section('§2 package.json and build.mjs');
{
    const pkg = JSON.parse(t.read('package.json'));
    t.check('./canvas', pkg.exports['./canvas'], { import: './dist/canvas.js', development: './canvas.js' });
    t.check('./flow', pkg.exports['./flow'], { import: './dist/flow.js', development: './flow.js' });
    const entries = /const ENTRIES = \[([^\]]*)\]/.exec(t.read('build.mjs'))?.[1] ?? '';
    const names = [...entries.matchAll(/'([^']+)'/g)].map((m) => m[1]);
    t.ok('build.mjs builds canvas and flow, and every entry it built before',
         ['core', 'host', 'wm', 'widgets', 'charts', 'tiles', 'editor', 'canvas', 'flow'].every((n) => names.includes(n)), names.join(','));
}

t.section('§3 the four stylesheet sections');
const SECTIONS = ['KIT', 'CANVAS', 'OUTLINE', 'LANES'];
const section = (text, name) => {
    const start = text.indexOf(`/* ══ FLOW · ${name} `);
    const endMark = `/* ══ end FLOW · ${name} ══ */`;
    const end = text.indexOf(endMark);
    return start < 0 || end < 0 ? null : { start, end: end + endMark.length, text: text.slice(start, end + endMark.length) };
};
{
    const sheets = { 'css/flexdesk.css': t.css('flexdesk.css'), 'css/base.css': t.css('base.css') };
    for (const [name, text] of Object.entries(sheets)) {
        const found = SECTIONS.map((s) => section(text, s));
        t.ok(`${name}: all four sections`, found.every(Boolean));
        if (!found.every(Boolean)) continue;
        t.ok(`${name}: in order`, found.every((s, i) => i === 0 || s.start > found[i - 1].end));
        t.ok(`${name}: two blank lines between one end marker and the next start`,
             found.slice(1).every((s, i) => text.slice(found[i].end, s.start) === '\n\n\n'));
        t.ok(`${name}: at the end of the sheet`, text.slice(found[3].end).trim() === '');
        t.ok(`${name}: each section once`, SECTIONS.every((s) => text.split(`/* ══ FLOW · ${s} `).length === 2));
    }
    for (const s of SECTIONS) {
        t.ok(`FLOW · ${s} is the same in base.css and flexdesk.css (hand-mirrored)`,
             section(sheets['css/base.css'], s)?.text === section(sheets['css/flexdesk.css'], s)?.text);
    }
}

t.section('§4 the tone tokens');
{
    const { TONES } = await import('../src/flow/kit/dom.js');
    const tokens = t.css('tokens.css');
    const missing = [];
    for (const tone of TONES) {
        for (const part of ['bg', 'fg', 'line', 'icon-bg', 'text-bg', 'dot']) {
            if (!new RegExp(`--twm-flow-${tone}-${part}\\s*:`).test(tokens)) missing.push(`--twm-flow-${tone}-${part}`);
        }
    }
    t.check('every tone, every part', missing, []);
    t.check('the six tones of the contract', [...TONES], ['violet', 'teal', 'amber', 'grey', 'blue', 'indigo']);
    const used = [...new Set([...t.css('flexdesk.css').matchAll(/var\((--twm-flow-[a-z0-9-]+)/g)].map((m) => m[1]))];
    t.check('every --twm-flow- token the sheet reads is defined', used.filter((v) => !new RegExp(`${v}\\s*:`).test(tokens)), []);
}

t.section('§5 the README');
{
    const readme = t.read('README.md');
    const at = readme.indexOf('\n## Flow editors\n');
    t.ok('a "Flow editors" section', at >= 0);
    const rest = readme.slice(at + 1);
    const next = rest.indexOf('\n## ', 3);
    const body = next < 0 ? rest : rest.slice(0, next);
    const subs = [...body.matchAll(/\n### (.+)\n/g)].map((m) => m[1]);
    t.check('its four subsections, in order', subs.slice(0, 4), ['The kit', 'The canvas editor', 'The outline editor',
                                                                  'The lane editor']);
}

t.section('§6 the kit\'s public API is the contract\'s');
{
    const kit = await import('../src/flow/kit/index.js');
    const flow = await import('../flow.js');
    const CONTRACT = [
        'createStepCatalogue', 'checkSettingsSchema', 'fieldsFromSchema', 'createWidgetRegistry', 'createSettingsPanel',
        'openStepPicker', 'createReferenceSyntax', 'TEMPLATE_REFERENCES', 'FORMULA_REFERENCES', 'PARAMETER_REFERENCES',
        'createChipInput', 'openValuePicker', 'alwaysBefore', 'groupFindings', 'createFindingsStrip', 'FlowHistory',
        'bindFlowKeys', 'ownsUndo', 'emptyGraph', 'normalise', 'serialise', 'nextId', 'addNode', 'removeNode',
        'connect', 'disconnect', 'inputNamesOf',
    ];
    t.check('every name 36 §3 lists is exported by the kit', CONTRACT.filter((n) => !(n in kit)), []);
    t.check('…and by @flexdesk/flow', CONTRACT.filter((n) => !(n in flow)), []);
}

t.done();
